### ISSUE TITLE
Status icon too big

### ISSUE THREAD

**Issue by manuelmayer-dev** [PhoenixWyllow/MacroDeck.SoundPad#1]
I think the status icon is too big compared to the status icon of other plugins.
The image itself should be 80x80 and the icon in it 56x56.
![Screenshot_2](https://user-images.githubusercontent.com/45011179/148695881-a50c91d4-0ca5-4d1e-9495-af711af8afcb.png)

No big problem but worth mentioning :)

**Comment by PhoenixWyllow** [comment]
Interesting. I had not considered the spacing but relied upon what I thought was correct sizing. I'll fix this with the next update.
