### ISSUE TITLE
[BUG] Sound list empty or not filtered by category

### ISSUE THREAD

**Issue by wsimon98** [PhoenixWyllow/MacroDeck.SoundPad#16]
**Describe the bug**
Soundpad Plugin no longer showing list of items in my Soundpad when attempting to add a new button with the plugin in Macro Deck. I've also noticed that the playlists even when it worked day one were not actually showing JUST what they had in their playlist. It would show all files inside soundpad. 

in the logs I found this reoccuring: [SoundPadPlugin] [Info] >> Unexpected end of file while parsing Name has occurred. Line 1188, position 193.

**To Reproduce**
1. Add a button in Macro Deck
2. Choose the play option
3. Choose your playlist
4. Choose a sound

**Expected behavior**
Should have stuff listed under each playlist when selecting a file to play with a button in Macro Deck

**Screenshots**
https://i.imgur.com/vF2O9ea.png

**Macro Deck (please complete the following information):**
 - Version: 2.12
 - Plugin version: 0.2.8

**Comment by PhoenixWyllow** [comment]
Thanks for bringing this up! I don't get the same issue - I see ALL the possible sounds, as you mentioned was the previous (unintended) behaviour.

I'll dig into this asap!
