### ISSUE TITLE
[BUG] Completely does not work

### ISSUE THREAD

**Issue by lolerfox** [PhoenixWyllow/MacroDeck.SoundPad#19]
**Describe the bug**
Well... literally it doesn't work unfortunately :(
I see that the work is kind of stopped... but it would be cool if it was fixed.

**LOG**
```
:05:05 [Macro Deck] [Info] >> Loading plugin SoundPadPlugin
22:05:05 [Macro Deck] [Info] >> ExtensionStoreDownloader: *** Installation of 1 package(s) done ***
22:05:55 [SoundPadPlugin] [Warning] >> PlayActionConfigViewModel.FetchCategoriesAsync: There is an error in XML document (1, 1). - Data at the root level is invalid. Line 1, position 1.
22:05:55 [Macro Deck] [Error] >> MacroDeck: ApplicationThreadException: Object reference not set to an instance of an object.
   at PW.MacroDeck.SoundPad.Views.PlayActionConfigView.PlayActionConfigView_Load(Object sender, EventArgs e) in C:\Users\Manuel\Desktop\Macro Deck Compiler\Temp\PhoenixWyllow.SoundPadPlugin\Views\PlayActionConfigView.cs:line 43
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_0(Object state)
22:05:58 [SoundPadPlugin] [Error] >> PlayActionConfigViewModel: config NOT saved
22:05:58 [SoundPadPlugin] [Error] >> PlayActionConfigViewModel: Object reference not set to an instance of an object.
22:05:59 [SoundPadPlugin] [Error] >> PlayActionConfigViewModel: config NOT saved
22:05:59 [SoundPadPlugin] [Error] >> PlayActionConfigViewModel: Object reference not set to an instance of an object.
22:05:59 [SoundPadPlugin] [Error] >> PlayActionConfigViewModel: config NOT saved
22:05:59 [SoundPadPlugin] [Error] >> PlayActionConfigViewModel: Object reference not set to an instance of an object.
22:05:59 [SoundPadPlugin] [Error] >> PlayActionConfigViewModel: config NOT saved
22:05:59 [SoundPadPlugin] [Error] >> PlayActionConfigViewModel: Object reference not set to an instance of an object.
22:06:01 [Macro Deck] [Info] >> Saved 1 profiles
```

**Screenshots**
![изображение](https://user-images.githubusercontent.com/60233774/230791913-9870813f-2b3b-4413-a2eb-5dc05320950e.png)

**Macro Deck (please complete the following information):**
 - Version: 2.12.0
 - Plugin version: 0.2.9

**Comment by PhoenixWyllow** [comment]
Hi,
I can't reproduce this on my pc.
Make sure you've restarted MD and SoundPad.
The error occurs because of this:
22:05:55 [SoundPadPlugin] [Warning] >> PlayActionConfigViewModel.FetchCategoriesAsync: There is an error in XML document (1, 1). - Data at the root level is invalid. Line 1, position 1.
Which edition of SoundPad do you have: Steam or standalone? Also, what version? 
The API should be the same, but I've received more bug reports from the standalone version...

**Comment by lolerfox** [comment]
Okay... excuse me... the problem was on my side... after reinstalling windows, everything works fine... Magic... ╮(￣ω￣;)╭

**Comment by PhoenixWyllow** [comment]
ok, that feels a little drastic, but I guess if it works... 🤷🏿 
Feel free to send more bug reports or feature requests if you have anything in particular you would like to see implemented!
